/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Minify `source`, optionally composing the result against `input_map`.
 *
 * Resolves with a [`MinifyResult`]. The work happens on the Node thread pool,
 * so many assets can be in flight at once without occupying the main thread.
 */
export declare function minify(filename: string, source: string, inputMap?: string | undefined | null, options?: MinifyOptions | undefined | null): Promise<MinifyResult>

export interface MinifyOptions {
  /** Run the compressor. Defaults to `true`. */
  compress?: boolean
  /** Shorten identifiers. Defaults to `true`. */
  mangle?: boolean
  /** Also mangle top-level identifiers. Only meaningful with `mangle`. */
  mangleToplevel?: boolean
  /** Produce a source map. Defaults to `true`. */
  sourcemap?: boolean
  /** Parse as an ES module rather than inferring from the file extension. */
  module?: boolean
}

export interface MinifyResult {
  /** The minified code. */
  code: string
  /**
   * The source map, as JSON. Already composed against `inputMap` when one was
   * supplied, so it maps minified output straight back to original sources.
   * `None` when source maps are switched off.
   */
  map?: string
  /** Non-fatal problems encountered while parsing. */
  warnings: Array<string>
}

/**
 * Blocking version of [`minify`]. Useful in scripts and tests; prefer the
 * asynchronous form anywhere throughput matters.
 *
 * `input_map` is the caller's existing map, as a JSON string: it must describe
 * how `source` relates to the original files. When present, the returned map
 * maps the minified output back to those original files in one hop.
 */
export declare function minifySync(filename: string, source: string, inputMap?: string | undefined | null, options?: MinifyOptions | undefined | null): MinifyResult
